vich_uploader:
    db_driver: orm

    mappings:
         mission_image:
             uri_prefix: /images/missions
             upload_destination: '%kernel.project_dir%/public/images/missions'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
